---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ORs/ORs.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/1401/articles/416911/master/file/figures/ORs/ORs.csv"
    folder_url: "/users/1401/articles/416911/master/folder/figures/ORs"
    treatFirstLineAsHeader: true
