---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/graph_structure_creation/graph_structure_creation.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/1401/articles/416911/master/file/figures/graph_structure_creation/graph_structure_creation.png"
