---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/graph construction/graph construction.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/1401/articles/416911/master/file/figures/graph%20construction/graph%20construction.png"
    folder_url: "/users/1401/articles/416911/master/folder/figures/graph construction"
