---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/FeNiSampleValidation/Figure7.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/1401/articles/416911/master/folder/figures/FeNiSampleValidation"
    url: "/users/1401/articles/416911/master/file/figures/FeNiSampleValidation/Figure7.png"
