---
version: 2
multicolumn: false
web-width: '800'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Figure9/Figure9.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/1401/articles/416911/master/folder/figures/Figure9"
    url: "/users/1401/articles/416911/master/file/figures/Figure9/Figure9.png"
